src/app.py
from flask import Flask, render_template

from src.common.database import Database
from src.models.alerts.views import alert_blueprint
from src.models.stores.views import store_blueprint
from src.models.users.views import user_blueprint

app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "secret"


@app.before_first_request
def initialize_database():
    Database.initialize()

@app.route('/')
def home():
    return render_template('home.html')


app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")
#app.test_request_context('/new')

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
def index():
    return "This is alert index page."


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_login
def create_alert():

    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.save_to_mongo()

    return render_template('alerts/create_alert.html')


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts', alert_id=alert_id))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)


@alert_blueprint.route('/check/<string:alert_id>')
@user_decorators.requires_login
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/items/views.py
from flask import Blueprint


item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass

src/models/stores/views.py
from flask import Blueprint


store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    return "This is store index page"


@store_blueprint.route('/store/<string:name>')
def store_page():
    pass

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template, redirect
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators
from src.models.users.user import User

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.html")


@user_blueprint.route('/register', methods=['POST', 'GET'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.html")


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('users/alert.html', alerts=alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))

@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="page-header mt-5">
        <h2 class="border-bottom pb-4">Alert
            <small class="font-weight-light">for {{alert.item.name}}</small>
        </h2>
    </div>

    <p>Last price found {{alert.item.price}} <br> Last checked on {{alert.last_checked.strftime("%d-%m-%Y at %H:%m")}}
    </p>
    {% if session['email'] in config.ADMINS %}
    <a class="btn btn-danger" href="{{url_for('alerts.deactivate_alert', alert_id=alert._id)}}" role="button">Deactivate Alert</a>
    {% endif %}
    <a class="btn btn-warning" href="{{url_for('alerts.check_alert_price', alert_id=alert._id)}}" role="button">Check Price</a>
</div>

{% endblock %}

src/templates/alerts/create_alert.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-md-center mt-5">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert name</label>
                <input id='name' class="form-control" type="text" name="name" placeholder="Name" required>
            </div>
            <div class="form-group">
                <label for="url">Url</label>
                <input id='url' class="form-control" type="text" name="url" placeholder="https://" required>
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input id='price_limit' class="form-control" type="text" name="price_limit" placeholder="45.0" required>
            </div>
             <button class="btn btn-default" type="submit" id="submit-button">Create new</button>
        </form>
    </div>
</div>
{% endblock %}

src/templates/alerts/edit_alert.html
{% extends "base.html" %}

{% block content %}
<p>Nothing here yet!</p>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing service</title>
    {% include 'html_dependencies.html' %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/" title="Home">Pricing</a>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{{ url_for('stores.index') }}">Stores</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('alerts.index') }}">Alerts</a></li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.user_alerts') }}">User Alerts</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout_user') }}">Logout</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.register_user') }}">Sign up</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.login_user') }}">Login</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron mt-5">
    <h1 class="display-4">Pricing Service</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
        featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a>
    </p>
</div>
{% endblock %}

src/templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

src/templates/stores/create_store.html
{% extends "base.html" %}

{% block content %}
<p>Nothing here yet!</p>
{% endblock %}

src/templates/stores/edit_store.html
{% extends "base.html" %}

{% block content %}
<p>Nothing here yet!</p>
{% endblock %}

src/templates/stores/store.html
{% extends "base.html" %}

{% block content %}
<p>Nothing here yet!</p>
{% endblock %}

src/templates/stores/store_list.html
{% extends "base.html" %}

{% block content %}
<p>Nothing here yet!</p>
{% endblock %}

src/templates/users/alert.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="page-header mt-5">
            <h2 class="border-bottom pb-4">Alerts <small class="font-weight-light">showing already existing alerts</small></h2>
        </div>
        <div class="list-group mb-3">
            {% for alert in alerts %}
            <a href="{{url_for('alerts.get_alert_page', alert_id=alert._id)}}" class="list-group-item list-group-item-action">
                <h4>Alert for {{alert.item.name}}</h4>
                <p>Last price found {{alert.item.price}} <br> Last checked on {{alert.last_checked.strftime("%d-%m-%Y at %H:%m")}}</p>
            </a>
            {% endfor %}
        </div>
        <a href="{{url_for('alerts.create_alert')}}" class="btn btn-success">Create new</a>
    </div>
{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-md-center mt-5">
    <div class="col-md-4">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input id='email' class="form-control" type="email" name="email" placeholder="Email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input id='password' class="form-control" type="password" name="password" placeholder="Password" required>
            </div>
             <button class="btn btn-default" type="submit" id="submit-button">Login</button>
        </form>
    </div>
</div>
{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-md-center mt-5">
    <div class="col-md-4">
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input id='email' class="form-control" type="email" name="email" placeholder="Email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input id='password' class="form-control" type="password" name="password" placeholder="Password" required>
            </div>
             <button class="btn btn-default" type="submit" id="submit-button">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}